### ISSUE TITLE
Utilizando o metadata @input

### ISSUE THREAD

**Issue by lucasfontesgaspareto** [danielschmitz/angular2-codigos#2]
@danielschmitz  Na pagina 75, capitulo 4. Ao utilizar do metadata `@input` no arquivo videolist.component.ts acontece o seguinte erro.

> Error: ReferenceError: Input is not defined(…)

Para corrigir este erro é necessário importar o `Input`. Ficaria desta forma certo?
`import {Component, Input} from '@angular/core';`

**Comment by danielschmitz** [comment]
Correto!

**Comment by danielschmitz** [comment]
PS: até então não uso o sistema de issues do github para os meus livros porque não sei ao certo se os leitores vão compreender como se usa.

mas acho que chegou a hora dos leitores aprenderem também git/github. Nao tem mais como viver sem essas ferramentas :)
